In [2]:
import numpy as np

In [3]:
a =np.array([0,1,2,3])
print(a)

[0 1 2 3]


why numpy is useful: Memory-efficient container that provide fast numerical operations


In [4]:
#python lists
L=range(1000)
%timeit [i**2 for i in L]

237 µs ± 5.84 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
a=np.arange(1000)
%timeit a**2

1.15 µs ± 5.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#  1. Creating  arrays

Manual constr. of array

In [6]:
#1-D

a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [7]:
# print dimension
a.ndim




1

In [8]:
# print shape
a.shape

(4,)

In [9]:
# print length
len(a)

4

In [10]:
#2-D, 3-D

b=np.array([[0,1,2],[3,4,5]])
b


array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 3)

In [13]:
len(b)  # return the size of the first dimension

2

In [14]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
c.ndim

3

In [16]:
c.shape

(2, 2, 2)

Functions for creating arrays

In [17]:
#using arange function 

# arange is a array-valued version of the built-in python range function

a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b=np.arange(1,10,2) # start , end(exclusive) , step
b

array([1, 3, 5, 7, 9])

In [19]:
#using linespace 
# It generate the value in range  0 to 1 and produce 6 values

a=np.linspace(0,1,6)  #start , end , no of points 
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [20]:
# comman arrays

# The default data type for the zeroes and ones are float

a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# The default data type for the zeroes and ones are float
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
c=np.eye(2) # returns a 2-D array with ones on the diagonal and zeroes elsewhere.
c

array([[1., 0.],
       [0., 1.]])

In [23]:
# 3 is no of rows , 2 is a number of columns , index of diagonal and zeroes elswhere

d=np.eye(3,2) 
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [26]:
#create array ysing diag functions

a=np.diag([1,2,3,4]) # construct a diagonal  array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
np.diag(a) #extracting the diagonal

array([1, 2, 3, 4])

In [29]:
# create array using random
# create an array of the given shape and populate it with random sample from uniform distribution


a=np.random.rand(4)
a

array([0.63484131, 0.14357073, 0.08594834, 0.59839314])

In [30]:
# return a sample (or samples) from the "standard normal distribution" **gaussion 
a=np.random.randn(4)
a

array([ 0.49176637,  2.26725893, -0.37357337,  1.63219922])

# 2. Basic Data Types

In [33]:
a=np.arange(10)
a.dtype

dtype('int32')

In [36]:
# you can explicitly specify which data-type you want:

a=np.arange(10,dtype=float)
a.dtype


dtype('float64')

In [37]:
b=np.array([True,False,True,False])   # Boolean Datatype 

print(b.dtype)

bool


# 3.Indexing and slicing

Indexing

In [39]:
a= np.arange(10)

print(a)
print(a[5])  # index start from 0

[0 1 2 3 4 5 6 7 8 9]
5


In [41]:
# for multi -D arrays, indexes are tuples of intergers:

a=np.diag([1,2,3])
print(a)
print(a[2,2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [42]:
a[2,1]=5  # assigning values

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

Slicing

In [44]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a[1:8:2]   # [startindex : endindex(exclusive) :step]

array([1, 3, 5, 7])

In [49]:
# we can also combine assignment and slicing:

a=np.arange(10)
a[5:] =10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [50]:
b=np.arange(5)

a[5:] =b[::-1]  # assigning

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [52]:
np.shares_memory(a,b)

False

In [54]:
b[0] =10
b

array([10,  1,  2,  3,  4])

In [57]:
a=np.arange(10)
c=a[::2].copy()  # force a copy
c


array([0, 2, 4, 6, 8])

# 5. Fancy Indexing

Numpy arrays can be indexed with slices, but also with boolean or integer arrays(masks).This method is called Fancy indexing. It creates copies not views.

Using Boolean Mask

In [58]:
a=np.random.randint(0,20,15)
a

array([ 6, 14, 17, 19, 15,  6,  4, 14,  7, 15, 10,  5, 11,  1,  5])

In [59]:
mask = (a% 2 ==0)


In [60]:
extract_from_a = a[mask]

extract_from_a

array([ 6, 14,  6,  4, 14, 10])

Indexing with a mask can be very useful to assign a new value to a sub-array:

In [61]:
a[mask] =-1
a

array([-1, -1, 17, 19, 15, -1, -1, -1,  7, 15, -1,  5, 11,  1,  5])

Indexing with an array of intergers

In [63]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
# Indexing can be done with an array of integers, where the same index is repeated several time:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [66]:
# New values can be assigned

a[[9,7]]= -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

# Elementwise Operations

1. Basic Operations


with scalrs

In [68]:
a=np.array([1,2,3,4]) # create an array
print(a)
print(a+1)

[1 2 3 4]
[2 3 4 5]


In [69]:
a**2

array([ 1,  4,  9, 16])

All arithmetic operates elementwise 

In [70]:
b=np.ones(4) +1
print(b)
print(a-b)

[2. 2. 2. 2.]
[-1.  0.  1.  2.]


In [71]:
a*b

array([2., 4., 6., 8.])

In [74]:
# Matrix multiplication

c=np.diag([1,2,3,4])

print(c*c)

print("-------------------")

print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
-------------------
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


comparisions

In [75]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
a == b

array([False,  True, False,  True])

In [77]:
a > b

array([False, False,  True, False])

In [78]:
# array-wise comparisions
a= np.array([1,2,3,4])
b=np.array([5,2,2,4])
c= np.array([1,2,3,4])

np.array_equal(a,b)

False

In [79]:
np.array_equal(a,c)

True

Logical Operations

In [80]:
a= np.array([1,1,0,0],dtype=bool)
b=np.array([1,0,1,0],dtype=bool)

np.logical_or(a,b)

array([ True,  True,  True, False])

In [82]:
np.logical_and(a,b)

array([ True, False, False, False])

Shape Mismatch

In [84]:
a= np.arrange(4)

a+np.array([1,2])

AttributeError: module 'numpy' has no attribute 'arrange'

# Basic Reductions

Computing sums


In [86]:
x= np.array([1,2,3,4])
np.sum(x)

10

In [87]:
# sum by rows and by columns

In [89]:
x= np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [90]:
x.sum(axis=0)  # columns first dimension

array([3, 3])

In [91]:
x.sum(axis=1)  # rows (second dimension)

array([2, 4])

Other reductions

In [93]:
x= np.array([1,3,2])
x.min()

1

In [95]:
x.max()

3

In [96]:
x.argmin() # index of minimum elements

0

In [98]:
x.argmax() # index of maximum elements

1

Logical Operations

In [100]:
np.all([True,True,False])

False

In [101]:
np.any([True,True,False])

True

In [104]:
#Note: can be used for array comparisons
a=np.zeros((50,50))
np.any(a != 0)

False

In [105]:
np.all(a == a)

True

In [106]:
a= np.array([1,2,3,2])
b=np.array([2,2,3,2])
c= np.array([6,4,4,5])
((a <= b) &(b <= c)).all()

True

Statistics

In [109]:
x= np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [110]:
np.median(x)

1.5

In [111]:
np.median(y, axis=-1)  # Last axis

array([2., 5.])

In [112]:
x.std()  # full population standard dev.

0.82915619758885

In [113]:
a=np.array([[1,2,3,],[4,5,6]])
a.ravel()
# return a cont. flatterned array. 

array([1, 2, 3, 4, 5, 6])

In [116]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
a.T # Tranpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [115]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

Reshaping

The inverse operation to flattering:

In [117]:
a


array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [120]:
b=a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [122]:
b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
b[0,0] =100
a


array([[100,   2,   3],
       [  4,   5,   6]])

Adding a Dimension

Indexing with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,


1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on
                                                                                        

In [125]:
z = np.array([1,2,3])
z

array([1, 2, 3])

In [126]:
z[ :, np.newaxis]

array([[1],
       [2],
       [3]])

In [130]:
z.shape


(3,)

Resizing

In [131]:
a=np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

Sorting Data

In [134]:
# sorting along an axis:

a=np.array([[5,4,6],[2,3,2]])
b=np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [136]:
# in -palce sort

a.sort(axis=1)